apiVersion: v1
kind: Service
metadata:
  name: external-logstash-outbound
  namespace: filebeat
spec:
  ports:
  - name: logstash-tcp
    protocol: TCP
    port: 5044
  - name: logstash-api
    protocol: TCP
    port: 9600
