apiVersion: v1
kind: Endpoints
metadata:
  name: external-logstash-outbound
  namespace: filebeat
subsets:
  - addresses:
    - ip: 193.122.99.195
    ports:
    - name: logstash-tcp
      protocol: TCP
      port: 5044
    - name: logstash-api
      protocol: TCP
      port: 9600
